# Pregunta1
#### ¿Cuál opción corresponde al servicio de salud al que llegaron más pacientes el día 1?

In [41]:
import pandas as pd

In [42]:
# Leer una hoja específica del archivo Excel
Hosp_sheet = pd.read_excel('Datos.xls', sheet_name='Hospitales')
Hosp_sheet

,Nombre Servicio de Salud,Nombre Establecimiento,Área Cuidados Intensivos Adultos,Área Cuidados Intermedios Adulto,Total Camas Críticas,Máxima cantidad de camas a aumetar,Costo de instalar una cama [MM$],Costo de operación anual de una cama [MM$],Costo diario GRD1 [MM$],Costo diario GRD2 [MM$],Costo diario GRD3 [MM$],Costo diario GRD4 [MM$],Costo diario GRD5 [MM$],Costo diario GRD6 [MM$],Costo diario GRD7 [MM$],Costo diario GRD8 [MM$],Costo diario GRD9 [MM$],Costo diario GRD10 [MM$]
0,Metropolitano Norte ...,Complejo Hospitalario San José,11,33,44,10,1407,47.2,0.593,0.509,0.367,0.492,0.524,0.405,0.571,0.474,0.498,0.305
1,Metropolitano Occidente ...,Hospital Adalberto Steeger (Talagante),6,11,17,5,1263,62.1,0.493,0.357,0.429,0.382,0.469,0.386,0.543,0.362,0.564,0.333
2,Metropolitano Occidente ...,Hospital Dr. Félix Bulnes Cerda,3,6,9,5,1310,65.9,0.580,0.325,0.375,0.409,0.561,0.362,0.328,0.314,0.536,0.436
3,Metropolitano Occidente ...,Hospital San Juan de Dios,29,47,76,30,1066,39.2,0.482,0.554,0.564,0.331,0.438,0.509,0.544,0.410,0.441,0.359
4,Metropolitano Occidente ...,Instituto Traumatológico Dr. Teodoro Gebauer,12,6,18,5,1433,55.5,0.407,0.449,0.468,0.433,0.573,0.392,0.409,0.391,0.418,0.334
5,Metropolitano Central ...,Hospital Clínico San Borja-Arriarán,17,26,43,10,1347,63.1,0.509,0.363,0.575,0.534,0.367,0.567,0.576,0.482,0.320,0.574
6,Metropolitano Central ...,Hospital de Urgencia Asistencia Pública Dr. Al...,24,20,44,10,1256,44.5,0.468,0.509,0.343,0.391,0.390,0.404,0.457,0.411,0.330,0.568
7,Metropolitano Central ...,Hospital el Carmen,6,12,18,4,1368,49.7,0.444,0.439,0.386,0.569,0.404,0.416,0.302,0.414,0.494,0.425
8,Metropolitano Oriente ...,Hospital Del Salvador,22,24,46,12,1075,45.4,0.444,0.339,0.345,0.544,0.458,0.531,0.340,0.491,0.377,0.443
9,Metropolitano Oriente ...,Hospital Dr. Luis Tisné B.,8,16,24,8,1056,56.2,0.386,0.477,0.491,0.312,0.452,0.362,0.435,0.305,0.482,0.421
10,Metropolitano Oriente ...,Instituto de Neurocirugía Dr. Alfonso Asenjo,12,11,23,8,1256,36.6,0.376,0.481,0.476,0.407,0.573,0.302,0.535,0.520,0.407,0.420
11,Metropolitano Oriente ...,Instituto Nacional de Enfermedades Respiratori...,15,29,44,15,1422,63.0,0.498,0.465,0.482,0.512,0.597,0.390,0.302,0.566,0.428,0.439
12,Metropolitano Sur ...,Hospital Barros Luco Trudeau,31,43,74,25,1319,42.9,0.551,0.339,0.587,0.416,0.545,0.306,0.347,0.548,0.501,0.419
13,Metropolitano Sur ...,Hospital de Enfermedades Infecciosas Dr. Lucio...,11,9,20,5,1193,61.6,0.540,0.407,0.590,0.492,0.458,0.361,0.420,0.452,0.331,0.330
14,Metropolitano Sur ...,Hospital Dr. Exequiel González Cortés,23,8,31,5,1304,51.9,0.398,0.343,0.454,0.493,0.489,0.444,0.323,0.572,0.500,0.310
15,Metropolitano Sur ...,Hospital El Pino,12,20,32,9,1074,66.1,0.546,0.599,0.550,0.383,0.569,0.442,0.543,0.504,0.590,0.549
16,Metropolitano Sur ...,Hospital Parroquial de San Bernardo,6,10,16,4,1051,47.0,0.541,0.546,0.533,0.411,0.534,0.466,0.313,0.500,0.523,0.310
17,Metropolitano Sur Oriente ...,Complejo Hospitalario Dr. Sótero del Río,20,35,55,12,1203,40.6,0.560,0.388,0.584,0.458,0.451,0.595,0.336,0.525,0.472,0.403
18,Metropolitano Sur Oriente ...,Hospital Clínico de la Florida,9,15,24,5,1028,60.0,0.527,0.552,0.431,0.594,0.331,0.341,0.580,0.528,0.537,0.505
19,Metropolitano Sur Oriente ...,Hospital Metropolitano ( ex Militar ),12,20,32,5,1093,46.3,0.549,0.553,0.471,0.346,0.582,0.331,0.456,0.394,0.410,0.563
20,Metropolitano Sur Oriente ...,Hospital Padre Alberto Hurtado (San Ramón),6,10,16,5,1166,43.2,0.479,0.579,0.387,0.509,0.571,0.516,0.584,0.382,0.462,0.424

In [43]:
HospitalxServ = Hosp_sheet[["Nombre Servicio de Salud","Nombre Establecimiento"]].groupby("Nombre Servicio de Salud") 
#de aqui saco las columnas que necesito para luego agruparlas
HxS = HospitalxServ.apply(lambda x: x).reset_index(drop=True)

In [44]:
Info_sheet = pd.read_excel('Datos.xls', sheet_name='Información Histórica') #Datos del dia de llegada
Info_sheet

,Número de llegada,Hospital al que llega,GRD,Día de llegada,Día de salida,Estadia
0,1,Instituto Traumatológico Dr. Teodoro Gebauer,GRD3,1,4,3
1,2,Hospital Clínico San Borja-Arriarán,GRD7,1,5,4
2,3,Hospital Dr. Luis Tisné B.,GRD7,1,5,4
3,4,Hospital Dr. Exequiel González Cortés,GRD10,1,11,10
4,5,Hospital Barros Luco Trudeau,GRD6,1,6,5
...,...,...,...,...,...,...
65529,65530,Hospital Clínico San Borja-Arriarán,GRD2,424,428,4
65530,65531,Hospital Dr. Exequiel González Cortés,GRD9,424,429,5
65531,65532,Hospital Del Salvador,GRD10,424,434,10
65532,65533,Hospital de Enfermedades Infecciosas Dr. Lucio...,GRD3,424,427,3
65533,65534,Hospital de Urgencia Asistencia Pública Dr. Al...,GRD7,424,428,4

In [45]:
df1 = Info_sheet.iloc[:146] #Recorto solo los del primer dia
#agrupo y cuento
result = df1.groupby(['Día de llegada', 'Hospital al que llega']).size().reset_index(name='Num_Pacientes') 
result.sort_values(by=["Num_Pacientes"],ascending = False) #Ordeno de mayor a menor

,Día de llegada,Hospital al que llega,Num_Pacientes
1,1,Complejo Hospitalario San José,16
3,1,Hospital Barros Luco Trudeau,14
4,1,Hospital Clínico San Borja-Arriarán,14
9,1,Hospital Dr. Luis Tisné B.,13
19,1,Instituto Traumatológico Dr. Teodoro Gebauer,11
6,1,Hospital Del Salvador,11
0,1,Complejo Hospitalario Dr. Sótero del Río,10
8,1,Hospital Dr. Félix Bulnes Cerda,10
16,1,Hospital de Urgencia Asistencia Pública Dr. Al...,9
18,1,Instituto Nacional de Enfermedades Respiratori...,7
7,1,Hospital Dr. Exequiel González Cortés,7
20,1,Instituto de Neurocirugía Dr. Alfonso Asenjo,5
14,1,Hospital San Juan de Dios,4
2,1,Hospital Adalberto Steeger (Talagante),4
12,1,Hospital Padre Alberto Hurtado (San Ramón),2
13,1,Hospital Parroquial de San Bernardo,2
17,1,Hospital el Carmen,2
10,1,Hospital El Pino,2
15,1,Hospital de Enfermedades Infecciosas Dr. Lucio...,1
11,1,Hospital Metropolitano ( ex Militar ),1
5,1,Hospital Clínico de la Florida,1

In [46]:
result = result.rename(columns={'Hospital al que llega' : 'Nombre Establecimiento'}) #primero modifico el nombre de las columnas para que se pueda hacer un merge
result

,Día de llegada,Nombre Establecimiento,Num_Pacientes
0,1,Complejo Hospitalario Dr. Sótero del Río,10
1,1,Complejo Hospitalario San José,16
2,1,Hospital Adalberto Steeger (Talagante),4
3,1,Hospital Barros Luco Trudeau,14
4,1,Hospital Clínico San Borja-Arriarán,14
5,1,Hospital Clínico de la Florida,1
6,1,Hospital Del Salvador,11
7,1,Hospital Dr. Exequiel González Cortés,7
8,1,Hospital Dr. Félix Bulnes Cerda,10
9,1,Hospital Dr. Luis Tisné B.,13
10,1,Hospital El Pino,2
11,1,Hospital Metropolitano ( ex Militar ),1
12,1,Hospital Padre Alberto Hurtado (San Ramón),2
13,1,Hospital Parroquial de San Bernardo,2
14,1,Hospital San Juan de Dios,4
15,1,Hospital de Enfermedades Infecciosas Dr. Lucio...,1
16,1,Hospital de Urgencia Asistencia Pública Dr. Al...,9
17,1,Hospital el Carmen,2
18,1,Instituto Nacional de Enfermedades Respiratori...,7
19,1,Instituto Traumatológico Dr. Teodoro Gebauer,11
20,1,Instituto de Neurocirugía Dr. Alfonso Asenjo,5

In [47]:
df_combinado = pd.merge(result, HxS, on='Nombre Establecimiento') #combino ambos df por la columna comun
df_combinado #DF combinado

,Día de llegada,Nombre Establecimiento,Num_Pacientes,Nombre Servicio de Salud
0,1,Complejo Hospitalario Dr. Sótero del Río,10,Metropolitano Sur Oriente ...
1,1,Complejo Hospitalario San José,16,Metropolitano Norte ...
2,1,Hospital Adalberto Steeger (Talagante),4,Metropolitano Occidente ...
3,1,Hospital Barros Luco Trudeau,14,Metropolitano Sur ...
4,1,Hospital Clínico San Borja-Arriarán,14,Metropolitano Central ...
5,1,Hospital Clínico de la Florida,1,Metropolitano Sur Oriente ...
6,1,Hospital Del Salvador,11,Metropolitano Oriente ...
7,1,Hospital Dr. Exequiel González Cortés,7,Metropolitano Sur ...
8,1,Hospital Dr. Félix Bulnes Cerda,10,Metropolitano Occidente ...
9,1,Hospital Dr. Luis Tisné B.,13,Metropolitano Oriente ...
10,1,Hospital El Pino,2,Metropolitano Sur ...
11,1,Hospital Metropolitano ( ex Militar ),1,Metropolitano Sur Oriente ...
12,1,Hospital Padre Alberto Hurtado (San Ramón),2,Metropolitano Sur Oriente ...
13,1,Hospital Parroquial de San Bernardo,2,Metropolitano Sur ...
14,1,Hospital San Juan de Dios,4,Metropolitano Occidente ...
15,1,Hospital de Enfermedades Infecciosas Dr. Lucio...,1,Metropolitano Sur ...
16,1,Hospital de Urgencia Asistencia Pública Dr. Al...,9,Metropolitano Central ...
17,1,Hospital el Carmen,2,Metropolitano Central ...
18,1,Instituto Nacional de Enfermedades Respiratori...,7,Metropolitano Oriente ...
19,1,Instituto Traumatológico Dr. Teodoro Gebauer,11,Metropolitano Occidente ...
20,1,Instituto de Neurocirugía Dr. Alfonso Asenjo,5,Metropolitano Oriente ...

In [48]:
result1 = df_combinado.groupby('Nombre Servicio de Salud')['Num_Pacientes'].sum().reset_index(name='Total_Pacientes')#Por ultimo agrupo y sumo los pacientes por servicio de salud
result1

                            Nombre Servicio de Salud  Total_Pacientes
0  Metropolitano Central                         ...               25
1  Metropolitano Norte                           ...               16
2  Metropolitano Occidente                       ...               29
3  Metropolitano Oriente                         ...               36
4  Metropolitano Sur                             ...               26
5  Metropolitano Sur Oriente                     ...               14

### Entonces el servicio de salud al que llegaron mas pacientes fue el Metropolitano Central

# Pregunta 2
### ¿Cuál cifra corresponde a la cantidad de pacientes de cada GRD 1, 7 y 10 y que han llegado históricamente al servicio de salud Metropolitano Sur?

In [49]:
Info_sheet = pd.read_excel('Datos.xls', sheet_name='Información Histórica') #Datos del dia de llegada
Info_sheet

,Número de llegada,Hospital al que llega,GRD,Día de llegada,Día de salida,Estadia
0,1,Instituto Traumatológico Dr. Teodoro Gebauer,GRD3,1,4,3
1,2,Hospital Clínico San Borja-Arriarán,GRD7,1,5,4
2,3,Hospital Dr. Luis Tisné B.,GRD7,1,5,4
3,4,Hospital Dr. Exequiel González Cortés,GRD10,1,11,10
4,5,Hospital Barros Luco Trudeau,GRD6,1,6,5
...,...,...,...,...,...,...
65529,65530,Hospital Clínico San Borja-Arriarán,GRD2,424,428,4
65530,65531,Hospital Dr. Exequiel González Cortés,GRD9,424,429,5
65531,65532,Hospital Del Salvador,GRD10,424,434,10
65532,65533,Hospital de Enfermedades Infecciosas Dr. Lucio...,GRD3,424,427,3
65533,65534,Hospital de Urgencia Asistencia Pública Dr. Al...,GRD7,424,428,4

In [50]:
result2 = Info_sheet.groupby(['Día de llegada', 'Hospital al que llega',"GRD"]).size().reset_index(name='Num_Pacientes') 
result2.sort_values(by=["Num_Pacientes"],ascending = False) #Ordeno de mayor a menor
result2 = result2.rename(columns={'Hospital al que llega' : 'Nombre Establecimiento'})
result2

,Día de llegada,Nombre Establecimiento,GRD,Num_Pacientes
0,1,Complejo Hospitalario Dr. Sótero del Río,GRD1,1
1,1,Complejo Hospitalario Dr. Sótero del Río,GRD2,1
2,1,Complejo Hospitalario Dr. Sótero del Río,GRD3,1
3,1,Complejo Hospitalario Dr. Sótero del Río,GRD4,1
4,1,Complejo Hospitalario Dr. Sótero del Río,GRD5,2
...,...,...,...,...
44277,424,Instituto Traumatológico Dr. Teodoro Gebauer,GRD4,1
44278,424,Instituto de Neurocirugía Dr. Alfonso Asenjo,GRD3,2
44279,424,Instituto de Neurocirugía Dr. Alfonso Asenjo,GRD5,2
44280,424,Instituto de Neurocirugía Dr. Alfonso Asenjo,GRD7,1
44281,424,Instituto de Neurocirugía Dr. Alfonso Asenjo,GRD9,2

In [51]:
df_combinado2 = pd.merge(result2, HxS, on='Nombre Establecimiento')
df_combinado2

,Día de llegada,Nombre Establecimiento,GRD,Num_Pacientes,Nombre Servicio de Salud
0,1,Complejo Hospitalario Dr. Sótero del Río,GRD1,1,Metropolitano Sur Oriente ...
1,1,Complejo Hospitalario Dr. Sótero del Río,GRD2,1,Metropolitano Sur Oriente ...
2,1,Complejo Hospitalario Dr. Sótero del Río,GRD3,1,Metropolitano Sur Oriente ...
3,1,Complejo Hospitalario Dr. Sótero del Río,GRD4,1,Metropolitano Sur Oriente ...
4,1,Complejo Hospitalario Dr. Sótero del Río,GRD5,2,Metropolitano Sur Oriente ...
...,...,...,...,...,...
44277,423,Instituto de Neurocirugía Dr. Alfonso Asenjo,GRD9,1,Metropolitano Oriente ...
44278,424,Instituto de Neurocirugía Dr. Alfonso Asenjo,GRD3,2,Metropolitano Oriente ...
44279,424,Instituto de Neurocirugía Dr. Alfonso Asenjo,GRD5,2,Metropolitano Oriente ...
44280,424,Instituto de Neurocirugía Dr. Alfonso Asenjo,GRD7,1,Metropolitano Oriente ...
44281,424,Instituto de Neurocirugía Dr. Alfonso Asenjo,GRD9,2,Metropolitano Oriente ...

In [52]:
result2 = df_combinado2.groupby(['Nombre Servicio de Salud',"GRD"])['Num_Pacientes'].sum().reset_index(name='Total_Pacientes')
result2

                             Nombre Servicio de Salud    GRD  Total_Pacientes
0   Metropolitano Central                         ...   GRD1             1095
1   Metropolitano Central                         ...  GRD10             1111
2   Metropolitano Central                         ...   GRD2             1138
3   Metropolitano Central                         ...   GRD3             1084
4   Metropolitano Central                         ...   GRD4             1076
5   Metropolitano Central                         ...   GRD5             1120
6   Metropolitano Central                         ...   GRD6             1125
7   Metropolitano Central                         ...   GRD7             1118
8   Metropolitano Central                         ...   GRD8             1096
9   Metropolitano Central                         ...   GRD9             1127
10  Metropolitano Norte                           ...   GRD1              464
11  Metropolitano Norte                           ...  GRD10              471
12  Metropolitano Norte                           ...   GRD2              451
13  Metropolitano Norte                           ...   GRD3              454
14  Metropolitano Norte                           ...   GRD4              466
15  Metropolitano Norte                           ...   GRD5              490
16  Metropolitano Norte                           ...   GRD6              443
17  Metropolitano Norte                           ...   GRD7              506
18  Metropolitano Norte                           ...   GRD8              427
19  Metropolitano Norte                           ...   GRD9              480
20  Metropolitano Occidente                       ...   GRD1             1159
21  Metropolitano Occidente                       ...  GRD10             1152
22  Metropolitano Occidente                       ...   GRD2             1123
23  Metropolitano Occidente                       ...   GRD3             1153
24  Metropolitano Occidente                       ...   GRD4             1109
25  Metropolitano Occidente                       ...   GRD5             1207
26  Metropolitano Occidente                       ...   GRD6             1108
27  Metropolitano Occidente                       ...   GRD7             1141
28  Metropolitano Occidente                       ...   GRD8             1152
29  Metropolitano Occidente                       ...   GRD9             1111
30  Metropolitano Oriente                         ...   GRD1             1622
31  Metropolitano Oriente                         ...  GRD10             1559
32  Metropolitano Oriente                         ...   GRD2             1591
33  Metropolitano Oriente                         ...   GRD3             1574
34  Metropolitano Oriente                         ...   GRD4             1603
35  Metropolitano Oriente                         ...   GRD5             1664
36  Metropolitano Oriente                         ...   GRD6             1604
37  Metropolitano Oriente                         ...   GRD7             1608
38  Metropolitano Oriente                         ...   GRD8             1665
39  Metropolitano Oriente                         ...   GRD9             1642
40  Metropolitano Sur                             ...   GRD1             1311
41  Metropolitano Sur                             ...  GRD10             1269
42  Metropolitano Sur                             ...   GRD2             1237
43  Metropolitano Sur                             ...   GRD3             1337
44  Metropolitano Sur                             ...   GRD4             1248
45  Metropolitano Sur                             ...   GRD5             1256
46  Metropolitano Sur                             ...   GRD6             1286
47  Metropolitano Sur                             ...   GRD7             1293
48  Metropolitano Sur                             ...   GRD8             1226
49  Metropolitano Sur                             ...   GRD9             1327
50  Metropolitano Sur Oriente                     ...   GRD1              936
51  Metropolitano Sur Oriente                     ...  GRD10              917
52  Metropolitano Sur Oriente                     ...   GRD2              929
53  Metropolitano Sur Oriente                     ...   GRD3              995
54  Metropolitano Sur Oriente                     ...   GRD4              920
55  Metropolitano Sur Oriente                     ...   GRD5              947
56  Metropolitano Sur Oriente                     ...   GRD6              936
57  Metropolitano Sur Oriente                     ...   GRD7              979
58  Metropolitano Sur Oriente                     ...   GRD8              931
59  Metropolitano Sur Oriente                     ...   GRD9              965

### 1311, 1293 y 1269  Respectivamen

# Pregunta 3
### ¿Cuál cifra corresponde a la mediana del número de pacientes que llegaron a cada servicio de salud?

### Primero necesito el numero de dias como indice

In [53]:
result3_1 = Info_sheet.groupby(['Día de llegada', 'Hospital al que llega']).size().reset_index(name='Num_Pacientes') 
result3_1
result3_1 = result3_1.rename(columns={'Hospital al que llega' : 'Nombre Establecimiento'})
df_combinado3 = pd.merge(result3_1, HxS, on='Nombre Establecimiento') #combino ambos df por la columna comun
df_combinado3.head()

,Día de llegada,Nombre Establecimiento,Num_Pacientes,Nombre Servicio de Salud
0,1,Complejo Hospitalario Dr. Sótero del Río,10,Metropolitano Sur Oriente ...
1,2,Complejo Hospitalario Dr. Sótero del Río,12,Metropolitano Sur Oriente ...
2,3,Complejo Hospitalario Dr. Sótero del Río,7,Metropolitano Sur Oriente ...
3,4,Complejo Hospitalario Dr. Sótero del Río,11,Metropolitano Sur Oriente ...
4,5,Complejo Hospitalario Dr. Sótero del Río,15,Metropolitano Sur Oriente ...

In [54]:
df_pivot= df_combinado3.pivot(columns='Nombre Servicio de Salud', values='Num_Pacientes')
df_pivot

Nombre Servicio de Salud,Metropolitano Central,Metropolitano Norte,Metropolitano Occidente,Metropolitano Oriente,Metropolitano Sur,Metropolitano Sur Oriente
0,NaN,NaN,NaN,NaN,NaN,10.0
1,NaN,NaN,NaN,NaN,NaN,12.0
2,NaN,NaN,NaN,NaN,NaN,7.0
3,NaN,NaN,NaN,NaN,NaN,11.0
4,NaN,NaN,NaN,NaN,NaN,15.0
...,...,...,...,...,...,...
8810,NaN,NaN,NaN,8.0,NaN,NaN
8811,NaN,NaN,NaN,4.0,NaN,NaN
8812,NaN,NaN,NaN,6.0,NaN,NaN
8813,NaN,NaN,NaN,9.0,NaN,NaN
8814,NaN,NaN,NaN,7.0,NaN,NaN

In [55]:
df_combinado3.groupby('Nombre Servicio de Salud')["Num_Pacientes"].median().reset_index(name='MEdiana')

                            Nombre Servicio de Salud  MEdiana
0  Metropolitano Central                         ...      9.0
1  Metropolitano Norte                           ...     11.0
2  Metropolitano Occidente                       ...      7.0
3  Metropolitano Oriente                         ...      9.0
4  Metropolitano Sur                             ...      5.0
5  Metropolitano Sur Oriente                     ...      5.0

## Trunca

# Pregunta 4

In [56]:
Info_sheet

,Número de llegada,Hospital al que llega,GRD,Día de llegada,Día de salida,Estadia
0,1,Instituto Traumatológico Dr. Teodoro Gebauer,GRD3,1,4,3
1,2,Hospital Clínico San Borja-Arriarán,GRD7,1,5,4
2,3,Hospital Dr. Luis Tisné B.,GRD7,1,5,4
3,4,Hospital Dr. Exequiel González Cortés,GRD10,1,11,10
4,5,Hospital Barros Luco Trudeau,GRD6,1,6,5
...,...,...,...,...,...,...
65529,65530,Hospital Clínico San Borja-Arriarán,GRD2,424,428,4
65530,65531,Hospital Dr. Exequiel González Cortés,GRD9,424,429,5
65531,65532,Hospital Del Salvador,GRD10,424,434,10
65532,65533,Hospital de Enfermedades Infecciosas Dr. Lucio...,GRD3,424,427,3
65533,65534,Hospital de Urgencia Asistencia Pública Dr. Al...,GRD7,424,428,4

In [57]:
import pandas as pd

valor_busqueda = 415
columna = 'Día de llegada'

indice_primera_aparicion = Info_sheet.index[Info_sheet[columna] == valor_busqueda].min()

print("El índice de la primera aparición es:", indice_primera_aparicion)

El índice de la primera aparición es: 63989

In [59]:
df4 = Info_sheet.iloc[63989:] #Recorto solo los ultimos 10 dias
result4 = df4.groupby(['Hospital al que llega','GRD',"Día de llegada","Estadia"]).size().reset_index(name='Num_Pacientes') 
result4

,Hospital al que llega,GRD,Día de llegada,Estadia,Num_Pacientes
0,Complejo Hospitalario Dr. Sótero del Río,GRD1,418,10,1
1,Complejo Hospitalario Dr. Sótero del Río,GRD1,419,10,1
2,Complejo Hospitalario Dr. Sótero del Río,GRD1,420,10,1
3,Complejo Hospitalario Dr. Sótero del Río,GRD1,422,10,2
4,Complejo Hospitalario Dr. Sótero del Río,GRD1,423,10,2
...,...,...,...,...,...
1027,Instituto de Neurocirugía Dr. Alfonso Asenjo,GRD9,418,5,2
1028,Instituto de Neurocirugía Dr. Alfonso Asenjo,GRD9,420,5,1
1029,Instituto de Neurocirugía Dr. Alfonso Asenjo,GRD9,422,5,1
1030,Instituto de Neurocirugía Dr. Alfonso Asenjo,GRD9,423,5,1
1031,Instituto de Neurocirugía Dr. Alfonso Asenjo,GRD9,424,5,2

### 8,88

# Pregunta 5
### ¿Cuál cifra corresponde al costo total de gastos, realizados en el hospital del Carmen, para la atención de los pacientes que llegaron los últimos 10 días (desde el día 415 al día 424)?

In [60]:
Hops_4= Hosp_sheet[7:8].transpose()
Hops_GRD = Hops_4[8:]
Hops_GRD = Hops_GRD.reset_index(drop=False)
nombres_columnas = ['GRD', 'Precio']
Hops_GRD.columns = nombres_columnas
Hops_GRD["GRD"] = ["GRD1","GRD2","GRD3", "GRD4","GRD5","GRD6","GRD7","GRD8","GRD9","GRD10"]
Hops_GRD

     GRD Precio
0   GRD1  0.444
1   GRD2  0.439
2   GRD3  0.386
3   GRD4  0.569
4   GRD5  0.404
5   GRD6  0.416
6   GRD7  0.302
7   GRD8  0.414
8   GRD9  0.494
9  GRD10  0.425

In [65]:
Hops_GRD['Precio'].mean()

0.4293

In [61]:
valor_busqueda = "Hospital el Carmen"
columna = 'Hospital al que llega'

indice_primera_aparicion = result4.index[result4[columna] == valor_busqueda].min()

print("El índice de la primera aparición es:", indice_primera_aparicion)

El índice de la primera aparición es: 839

In [80]:
result5 =result4.iloc[839:868]
result5.head()

    Hospital al que llega    GRD  Día de llegada  Estadia  Num_Pacientes
839    Hospital el Carmen   GRD1             419       10              1
840    Hospital el Carmen   GRD1             423       10              1
841    Hospital el Carmen  GRD10             416       10              1
842    Hospital el Carmen  GRD10             419       10              1
843    Hospital el Carmen   GRD2             417        4              1

In [81]:
df_combinado5 = pd.merge(result5, Hops_GRD, on='GRD') #combino ambos df por la columna comun
df_combinado5.head()

  Hospital al que llega    GRD  Día de llegada  Estadia  Num_Pacientes Precio
0    Hospital el Carmen   GRD1             419       10              1  0.444
1    Hospital el Carmen   GRD1             423       10              1  0.444
2    Hospital el Carmen  GRD10             416       10              1  0.425
3    Hospital el Carmen  GRD10             419       10              1  0.425
4    Hospital el Carmen   GRD2             417        4              1  0.439

In [64]:

df_combinado5["Costo Total"] = df_combinado5["Num_Pacientes"]* df_combinado5["Precio"]*df_combinado5["Estadia"]
df_combinado5["Costo Total"].sum()

77.776

### 77.776

# Pregunta 6
### ¿Cuál es el costo total de gastos del servicio de salud Metropolitano Central, para la atención de los pacientes, que llegaron los últimos 10 días utilizando los costos diarios de atención por GRD promedio del sistema (desde el día 415 al día 424)?

### Hay que calcular los costos diarios por GRD de todo el sistema

In [146]:
df4 # ULtimos 10 dias
df4 = df4.rename(columns={'Hospital al que llega' : 'Nombre Establecimiento'})
df_combinado6 = pd.merge(df4, HxS, on='Nombre Establecimiento') #combino ambos df por la columna comun
df_combinado6

,Número de llegada,Nombre Establecimiento,GRD,Día de llegada,Día de salida,Estadia,Nombre Servicio de Salud
0,63990,Complejo Hospitalario Dr. Sótero del Río,GRD2,415,419,4,Metropolitano Sur Oriente ...
1,63995,Complejo Hospitalario Dr. Sótero del Río,GRD8,415,419,4,Metropolitano Sur Oriente ...
2,64006,Complejo Hospitalario Dr. Sótero del Río,GRD2,415,419,4,Metropolitano Sur Oriente ...
3,64015,Complejo Hospitalario Dr. Sótero del Río,GRD9,415,420,5,Metropolitano Sur Oriente ...
4,64032,Complejo Hospitalario Dr. Sótero del Río,GRD3,415,418,3,Metropolitano Sur Oriente ...
...,...,...,...,...,...,...,...
1540,65375,Hospital Metropolitano ( ex Militar ),GRD6,423,428,5,Metropolitano Sur Oriente ...
1541,65446,Hospital Metropolitano ( ex Militar ),GRD1,423,433,10,Metropolitano Sur Oriente ...
1542,65447,Hospital Metropolitano ( ex Militar ),GRD10,423,433,10,Metropolitano Sur Oriente ...
1543,65461,Hospital Metropolitano ( ex Militar ),GRD5,424,428,4,Metropolitano Sur Oriente ...
1544,65517,Hospital Metropolitano ( ex Militar ),GRD2,424,428,4,Metropolitano Sur Oriente ...

In [145]:
result6 = df_combinado6.groupby(['Nombre Servicio de Salud','GRD',"Estadia"]).size().reset_index(name='Num_Pacientes') 
Central = result6[:10]

,Nombre Servicio de Salud,GRD,Estadia,Num_Pacientes
0,Metropolitano Central ...,GRD1,10,1
1,Metropolitano Central ...,GRD10,10,1
2,Metropolitano Central ...,GRD2,4,1
3,Metropolitano Central ...,GRD3,3,1
4,Metropolitano Central ...,GRD4,6,1
5,Metropolitano Central ...,GRD5,4,1
6,Metropolitano Central ...,GRD6,5,1
7,Metropolitano Central ...,GRD7,4,1
8,Metropolitano Central ...,GRD8,4,1
9,Metropolitano Central ...,GRD9,5,1

In [126]:
GRDs = Hosp_sheet.iloc[:,8:].columns.tolist()
print(GRDs)

['Costo diario GRD1 [MM$]', 'Costo diario GRD2 [MM$]', 'Costo diario GRD3 [MM$]', 'Costo diario GRD4 [MM$]', 'Costo diario GRD5 [MM$]', 'Costo diario GRD6 [MM$]', 'Costo diario GRD7 [MM$]', 'Costo diario GRD8 [MM$]', 'Costo diario GRD9 [MM$]', 'Costo diario GRD10 [MM$]']

In [136]:
Promedios_xGRD = Hosp_sheet.groupby('Nombre Servicio de Salud')[GRDs].mean()
Grds_central = Promedios_xGRD[0:1].transpose() #selecciono solo los del Central
Grds_central = Grds_central.reset_index(drop=False)
Grds_central #Tabla de constes promedios de central por GRD

Nombre Servicio de Salud,index,Metropolitano Central
0,Costo diario GRD1 [MM$],0.473667
1,Costo diario GRD2 [MM$],0.437000
2,Costo diario GRD3 [MM$],0.434667
3,Costo diario GRD4 [MM$],0.498000
4,Costo diario GRD5 [MM$],0.387000
5,Costo diario GRD6 [MM$],0.462333
6,Costo diario GRD7 [MM$],0.445000
7,Costo diario GRD8 [MM$],0.435667
8,Costo diario GRD9 [MM$],0.381333
9,Costo diario GRD10 [MM$],0.522333

In [138]:
nombres_columnas = ['GRD', 'Precio']
Grds_central.columns = nombres_columnas
Grds_central["GRD"] = ["GRD1","GRD2","GRD3", "GRD4","GRD5","GRD6","GRD7","GRD8","GRD9","GRD10"]
Grds_central

     GRD    Precio
0   GRD1  0.473667
1   GRD2  0.437000
2   GRD3  0.434667
3   GRD4  0.498000
4   GRD5  0.387000
5   GRD6  0.462333
6   GRD7  0.445000
7   GRD8  0.435667
8   GRD9  0.381333
9  GRD10  0.522333

In [139]:
df_combinado6 = pd.merge(Grds_central, Central, on='GRD') #combino ambos df por la columna comun
df_combinado6

,GRD,Precio,Nombre Servicio de Salud,Estadia,Num_Pacientes
0,GRD1,0.473667,Metropolitano Central ...,10,26
1,GRD2,0.437000,Metropolitano Central ...,4,30
2,GRD3,0.434667,Metropolitano Central ...,3,25
3,GRD4,0.498000,Metropolitano Central ...,6,29
4,GRD5,0.387000,Metropolitano Central ...,4,20
5,GRD6,0.462333,Metropolitano Central ...,5,25
6,GRD7,0.445000,Metropolitano Central ...,4,32
7,GRD8,0.435667,Metropolitano Central ...,4,28
8,GRD9,0.381333,Metropolitano Central ...,5,25
9,GRD10,0.522333,Metropolitano Central ...,10,28

In [144]:
df_combinado6["Costo Total"] = df_combinado6["Num_Pacientes"]* df_combinado6["Precio"]*df_combinado6["Estadia"]
df_combinado6['Costo Total'].sum()

683.2716666666666

# Pregunta7
### ¿Qué servicio de salud gastó más dinero, para la atención de los pacientes que llegaron los últimos 10 días utilizando los costos diarios de atención por GRD promedio de cada sistema (desde el día 415 al día 424)?  #### Se vuelve generica la 6

In [149]:
df_combinado6

,Número de llegada,Nombre Establecimiento,GRD,Día de llegada,Día de salida,Estadia,Nombre Servicio de Salud
0,63990,Complejo Hospitalario Dr. Sótero del Río,GRD2,415,419,4,Metropolitano Sur Oriente ...
1,63995,Complejo Hospitalario Dr. Sótero del Río,GRD8,415,419,4,Metropolitano Sur Oriente ...
2,64006,Complejo Hospitalario Dr. Sótero del Río,GRD2,415,419,4,Metropolitano Sur Oriente ...
3,64015,Complejo Hospitalario Dr. Sótero del Río,GRD9,415,420,5,Metropolitano Sur Oriente ...
4,64032,Complejo Hospitalario Dr. Sótero del Río,GRD3,415,418,3,Metropolitano Sur Oriente ...
...,...,...,...,...,...,...,...
1540,65375,Hospital Metropolitano ( ex Militar ),GRD6,423,428,5,Metropolitano Sur Oriente ...
1541,65446,Hospital Metropolitano ( ex Militar ),GRD1,423,433,10,Metropolitano Sur Oriente ...
1542,65447,Hospital Metropolitano ( ex Militar ),GRD10,423,433,10,Metropolitano Sur Oriente ...
1543,65461,Hospital Metropolitano ( ex Militar ),GRD5,424,428,4,Metropolitano Sur Oriente ...
1544,65517,Hospital Metropolitano ( ex Militar ),GRD2,424,428,4,Metropolitano Sur Oriente ...

In [177]:
result7 = df_combinado6.groupby(['Nombre Servicio de Salud','GRD',"Estadia"]).size().reset_index(name='Num_Pacientes')
result7 #para mergear con la columna de costos medios de GRD

,Nombre Servicio de Salud,GRD,Estadia,Num_Pacientes
0,Metropolitano Central ...,GRD1,10,26
1,Metropolitano Central ...,GRD10,10,28
2,Metropolitano Central ...,GRD2,4,30
3,Metropolitano Central ...,GRD3,3,25
4,Metropolitano Central ...,GRD4,6,29
5,Metropolitano Central ...,GRD5,4,20
6,Metropolitano Central ...,GRD6,5,25
7,Metropolitano Central ...,GRD7,4,32
8,Metropolitano Central ...,GRD8,4,28
9,Metropolitano Central ...,GRD9,5,25
10,Metropolitano Norte ...,GRD1,10,12
11,Metropolitano Norte ...,GRD10,10,16
12,Metropolitano Norte ...,GRD2,4,10
13,Metropolitano Norte ...,GRD3,3,12
14,Metropolitano Norte ...,GRD4,6,8
15,Metropolitano Norte ...,GRD5,4,8
16,Metropolitano Norte ...,GRD6,5,12
17,Metropolitano Norte ...,GRD7,4,13
18,Metropolitano Norte ...,GRD8,4,8
19,Metropolitano Norte ...,GRD9,5,7
20,Metropolitano Occidente ...,GRD1,10,32
21,Metropolitano Occidente ...,GRD10,10,20
22,Metropolitano Occidente ...,GRD2,4,26
23,Metropolitano Occidente ...,GRD3,3,33
24,Metropolitano Occidente ...,GRD4,6,20
25,Metropolitano Occidente ...,GRD5,4,28
26,Metropolitano Occidente ...,GRD6,5,25
27,Metropolitano Occidente ...,GRD7,4,34
28,Metropolitano Occidente ...,GRD8,4,22
29,Metropolitano Occidente ...,GRD9,5,17
30,Metropolitano Oriente ...,GRD1,10,32
31,Metropolitano Oriente ...,GRD10,10,41
32,Metropolitano Oriente ...,GRD2,4,39
33,Metropolitano Oriente ...,GRD3,3,36
34,Metropolitano Oriente ...,GRD4,6,31
35,Metropolitano Oriente ...,GRD5,4,35
36,Metropolitano Oriente ...,GRD6,5,42
37,Metropolitano Oriente ...,GRD7,4,44
38,Metropolitano Oriente ...,GRD8,4,39
39,Metropolitano Oriente ...,GRD9,5,37
40,Metropolitano Sur ...,GRD1,10,23
41,Metropolitano Sur ...,GRD10,10,33
42,Metropolitano Sur ...,GRD2,4,35
43,Metropolitano Sur ...,GRD3,3,37
44,Metropolitano Sur ...,GRD4,6,31
45,Metropolitano Sur ...,GRD5,4,34
46,Metropolitano Sur ...,GRD6,5,33
47,Metropolitano Sur ...,GRD7,4,26
48,Metropolitano Sur ...,GRD8,4,31
49,Metropolitano Sur ...,GRD9,5,40
50,Metropolitano Sur Oriente ...,GRD1,10,26
51,Metropolitano Sur Oriente ...,GRD10,10,27
52,Metropolitano Sur Oriente ...,GRD2,4,15
53,Metropolitano Sur Oriente ...,GRD3,3,24
54,Metropolitano Sur Oriente ...,GRD4,6,19
55,Metropolitano Sur Oriente ...,GRD5,4,18
56,Metropolitano Sur Oriente ...,GRD6,5,24
57,Metropolitano Sur Oriente ...,GRD7,4,26
58,Metropolitano Sur Oriente ...,GRD8,4,21
59,Metropolitano Sur Oriente ...,GRD9,5,15

In [241]:
result7['Etiqueta'] = result7['GRD'] + '-' + result7['Nombre Servicio de Salud']
result7_1 = result7.iloc[:,2:-1]
nombres_columnas = ['Estadia', 'Num_Pacientes','Etiqueta']
result7_1.columns = nombres_columnas
result7_1

    Estadia  Num_Pacientes                                           Etiqueta
0        10             26  GRD1-Metropolitano Central                    ...
1        10             28  GRD10-Metropolitano Central                   ...
2         4             30  GRD2-Metropolitano Central                    ...
3         3             25  GRD3-Metropolitano Central                    ...
4         6             29  GRD4-Metropolitano Central                    ...
5         4             20  GRD5-Metropolitano Central                    ...
6         5             25  GRD6-Metropolitano Central                    ...
7         4             32  GRD7-Metropolitano Central                    ...
8         4             28  GRD8-Metropolitano Central                    ...
9         5             25  GRD9-Metropolitano Central                    ...
10       10             12  GRD1-Metropolitano Norte                      ...
11       10             16  GRD10-Metropolitano Norte                     ...
12        4             10  GRD2-Metropolitano Norte                      ...
13        3             12  GRD3-Metropolitano Norte                      ...
14        6              8  GRD4-Metropolitano Norte                      ...
15        4              8  GRD5-Metropolitano Norte                      ...
16        5             12  GRD6-Metropolitano Norte                      ...
17        4             13  GRD7-Metropolitano Norte                      ...
18        4              8  GRD8-Metropolitano Norte                      ...
19        5              7  GRD9-Metropolitano Norte                      ...
20       10             32  GRD1-Metropolitano Occidente                  ...
21       10             20  GRD10-Metropolitano Occidente                 ...
22        4             26  GRD2-Metropolitano Occidente                  ...
23        3             33  GRD3-Metropolitano Occidente                  ...
24        6             20  GRD4-Metropolitano Occidente                  ...
25        4             28  GRD5-Metropolitano Occidente                  ...
26        5             25  GRD6-Metropolitano Occidente                  ...
27        4             34  GRD7-Metropolitano Occidente                  ...
28        4             22  GRD8-Metropolitano Occidente                  ...
29        5             17  GRD9-Metropolitano Occidente                  ...
30       10             32  GRD1-Metropolitano Oriente                    ...
31       10             41  GRD10-Metropolitano Oriente                   ...
32        4             39  GRD2-Metropolitano Oriente                    ...
33        3             36  GRD3-Metropolitano Oriente                    ...
34        6             31  GRD4-Metropolitano Oriente                    ...
35        4             35  GRD5-Metropolitano Oriente                    ...
36        5             42  GRD6-Metropolitano Oriente                    ...
37        4             44  GRD7-Metropolitano Oriente                    ...
38        4             39  GRD8-Metropolitano Oriente                    ...
39        5             37  GRD9-Metropolitano Oriente                    ...
40       10             23  GRD1-Metropolitano Sur                        ...
41       10             33  GRD10-Metropolitano Sur                       ...
42        4             35  GRD2-Metropolitano Sur                        ...
43        3             37  GRD3-Metropolitano Sur                        ...
44        6             31  GRD4-Metropolitano Sur                        ...
45        4             34  GRD5-Metropolitano Sur                        ...
46        5             33  GRD6-Metropolitano Sur                        ...
47        4             26  GRD7-Metropolitano Sur                        ...
48        4             31  GRD8-Metropolitano Sur                        ...
49        5             40  GRD9-Metropolitano Sur                        ...
50       10             26  GRD1-Metropolitano Sur Oriente                ...
51       10             27  GRD10-Metropolitano Sur Oriente               ...
52        4             15  GRD2-Metropolitano Sur Oriente                ...
53        3             24  GRD3-Metropolitano Sur Oriente                ...
54        6             19  GRD4-Metropolitano Sur Oriente                ...
55        4             18  GRD5-Metropolitano Sur Oriente                ...
56        5             24  GRD6-Metropolitano Sur Oriente                ...
57        4             26  GRD7-Metropolitano Sur Oriente                ...
58        4             21  GRD8-Metropolitano Sur Oriente                ...
59        5             15  GRD9-Metropolitano Sur Oriente                ...

In [200]:
GRD7 = Hosp_sheet.groupby('Nombre Servicio de Salud')[GRDs].mean()
GRD7.transpose()
GRD7_index = GRD7.transpose().reset_index(drop=False)
nuevos_nombres = ['GRD'] + list(GRD7_index.columns[1:])
GRD7_index.columns = nuevos_nombres
GRD7_index

,GRD,Metropolitano Central,Metropolitano Norte,Metropolitano Occidente,Metropolitano Oriente,Metropolitano Sur,Metropolitano Sur Oriente
0,Costo diario GRD1 [MM$],0.473667,0.593,0.49050,0.42600,0.5152,0.52875
1,Costo diario GRD2 [MM$],0.437000,0.509,0.42125,0.44050,0.4468,0.51800
2,Costo diario GRD3 [MM$],0.434667,0.367,0.45900,0.44850,0.5428,0.46825
3,Costo diario GRD4 [MM$],0.498000,0.492,0.38875,0.44375,0.4390,0.47675
4,Costo diario GRD5 [MM$],0.387000,0.524,0.51025,0.52000,0.5190,0.48375
5,Costo diario GRD6 [MM$],0.462333,0.405,0.41225,0.39625,0.4038,0.44575
6,Costo diario GRD7 [MM$],0.445000,0.571,0.45600,0.40300,0.3892,0.48900
7,Costo diario GRD8 [MM$],0.435667,0.474,0.36925,0.47050,0.5152,0.45725
8,Costo diario GRD9 [MM$],0.381333,0.498,0.48975,0.42350,0.4890,0.47025
9,Costo diario GRD10 [MM$],0.522333,0.305,0.36550,0.43075,0.3836,0.47375

In [201]:
GRD7_index["GRD"] = ["GRD1","GRD2","GRD3", "GRD4","GRD5","GRD6","GRD7","GRD8","GRD9","GRD10"]
GRD7_index

,GRD,Metropolitano Central,Metropolitano Norte,Metropolitano Occidente,Metropolitano Oriente,Metropolitano Sur,Metropolitano Sur Oriente
0,GRD1,0.473667,0.593,0.49050,0.42600,0.5152,0.52875
1,GRD2,0.437000,0.509,0.42125,0.44050,0.4468,0.51800
2,GRD3,0.434667,0.367,0.45900,0.44850,0.5428,0.46825
3,GRD4,0.498000,0.492,0.38875,0.44375,0.4390,0.47675
4,GRD5,0.387000,0.524,0.51025,0.52000,0.5190,0.48375
5,GRD6,0.462333,0.405,0.41225,0.39625,0.4038,0.44575
6,GRD7,0.445000,0.571,0.45600,0.40300,0.3892,0.48900
7,GRD8,0.435667,0.474,0.36925,0.47050,0.5152,0.45725
8,GRD9,0.381333,0.498,0.48975,0.42350,0.4890,0.47025
9,GRD10,0.522333,0.305,0.36550,0.43075,0.3836,0.47375

In [202]:
GRD7_index

,GRD,Metropolitano Central,Metropolitano Norte,Metropolitano Occidente,Metropolitano Oriente,Metropolitano Sur,Metropolitano Sur Oriente
0,GRD1,0.473667,0.593,0.49050,0.42600,0.5152,0.52875
1,GRD2,0.437000,0.509,0.42125,0.44050,0.4468,0.51800
2,GRD3,0.434667,0.367,0.45900,0.44850,0.5428,0.46825
3,GRD4,0.498000,0.492,0.38875,0.44375,0.4390,0.47675
4,GRD5,0.387000,0.524,0.51025,0.52000,0.5190,0.48375
5,GRD6,0.462333,0.405,0.41225,0.39625,0.4038,0.44575
6,GRD7,0.445000,0.571,0.45600,0.40300,0.3892,0.48900
7,GRD8,0.435667,0.474,0.36925,0.47050,0.5152,0.45725
8,GRD9,0.381333,0.498,0.48975,0.42350,0.4890,0.47025
9,GRD10,0.522333,0.305,0.36550,0.43075,0.3836,0.47375

In [233]:
# Obtener las etiquetas de las columnas (excepto la primera)
columnas = GRD7_index.columns[1:]
# Crear una lista para almacenar los datos del DataFrame resultante
datos_resultantes = []

# Iterar sobre las columnas y concatenar la primera columna original con el nombre de cada columna
for columna in columnas:
    etiqueta = GRD7_index['GRD'].astype(str) + '-' + columna
    valores = GRD7_index[columna].tolist()
    datos_resultantes.extend(list(zip(etiqueta, valores)))

# Crear el DataFrame resultante
df_resultante = pd.DataFrame(datos_resultantes, columns=['Etiqueta', 'Valor'])

# Mostrar el DataFrame resultante de 60x2
df_resultante

Index(['Metropolitano Central                             ',
       'Metropolitano Norte                               ',
       'Metropolitano Occidente                           ',
       'Metropolitano Oriente                             ',
       'Metropolitano Sur                                 ',
       'Metropolitano Sur Oriente                         '],
      dtype='object')

                                             Etiqueta     Valor
0   GRD1-Metropolitano Central                    ...  0.473667
1   GRD2-Metropolitano Central                    ...  0.437000
2   GRD3-Metropolitano Central                    ...  0.434667
3   GRD4-Metropolitano Central                    ...  0.498000
4   GRD5-Metropolitano Central                    ...  0.387000
5   GRD6-Metropolitano Central                    ...  0.462333
6   GRD7-Metropolitano Central                    ...  0.445000
7   GRD8-Metropolitano Central                    ...  0.435667
8   GRD9-Metropolitano Central                    ...  0.381333
9   GRD10-Metropolitano Central                   ...  0.522333
10  GRD1-Metropolitano Norte                      ...  0.593000
11  GRD2-Metropolitano Norte                      ...  0.509000
12  GRD3-Metropolitano Norte                      ...  0.367000
13  GRD4-Metropolitano Norte                      ...  0.492000
14  GRD5-Metropolitano Norte                      ...  0.524000
15  GRD6-Metropolitano Norte                      ...  0.405000
16  GRD7-Metropolitano Norte                      ...  0.571000
17  GRD8-Metropolitano Norte                      ...  0.474000
18  GRD9-Metropolitano Norte                      ...  0.498000
19  GRD10-Metropolitano Norte                     ...  0.305000
20  GRD1-Metropolitano Occidente                  ...  0.490500
21  GRD2-Metropolitano Occidente                  ...  0.421250
22  GRD3-Metropolitano Occidente                  ...  0.459000
23  GRD4-Metropolitano Occidente                  ...  0.388750
24  GRD5-Metropolitano Occidente                  ...  0.510250
25  GRD6-Metropolitano Occidente                  ...  0.412250
26  GRD7-Metropolitano Occidente                  ...  0.456000
27  GRD8-Metropolitano Occidente                  ...  0.369250
28  GRD9-Metropolitano Occidente                  ...  0.489750
29  GRD10-Metropolitano Occidente                 ...  0.365500
30  GRD1-Metropolitano Oriente                    ...  0.426000
31  GRD2-Metropolitano Oriente                    ...  0.440500
32  GRD3-Metropolitano Oriente                    ...  0.448500
33  GRD4-Metropolitano Oriente                    ...  0.443750
34  GRD5-Metropolitano Oriente                    ...  0.520000
35  GRD6-Metropolitano Oriente                    ...  0.396250
36  GRD7-Metropolitano Oriente                    ...  0.403000
37  GRD8-Metropolitano Oriente                    ...  0.470500
38  GRD9-Metropolitano Oriente                    ...  0.423500
39  GRD10-Metropolitano Oriente                   ...  0.430750
40  GRD1-Metropolitano Sur                        ...  0.515200
41  GRD2-Metropolitano Sur                        ...  0.446800
42  GRD3-Metropolitano Sur                        ...  0.542800
43  GRD4-Metropolitano Sur                        ...  0.439000
44  GRD5-Metropolitano Sur                        ...  0.519000
45  GRD6-Metropolitano Sur                        ...  0.403800
46  GRD7-Metropolitano Sur                        ...  0.389200
47  GRD8-Metropolitano Sur                        ...  0.515200
48  GRD9-Metropolitano Sur                        ...  0.489000
49  GRD10-Metropolitano Sur                       ...  0.383600
50  GRD1-Metropolitano Sur Oriente                ...  0.528750
51  GRD2-Metropolitano Sur Oriente                ...  0.518000
52  GRD3-Metropolitano Sur Oriente                ...  0.468250
53  GRD4-Metropolitano Sur Oriente                ...  0.476750
54  GRD5-Metropolitano Sur Oriente                ...  0.483750
55  GRD6-Metropolitano Sur Oriente                ...  0.445750
56  GRD7-Metropolitano Sur Oriente                ...  0.489000
57  GRD8-Metropolitano Sur Oriente                ...  0.457250
58  GRD9-Metropolitano Sur Oriente                ...  0.470250
59  GRD10-Metropolitano Sur Oriente               ...  0.473750

In [251]:
Reult7_F = pd.merge(df_resultante, result7_1, on='Etiqueta') #combino ambos df por la columna comun
Reult7_F['Costo'] = Reult7_F['Valor'] * Reult7_F['Estadia'] * Reult7_F['Num_Pacientes']
Reult7_F

,Etiqueta,Valor,Estadia,Num_Pacientes,Costo
0,GRD1-Metropolitano Central ...,0.473667,10,26,123.153333
1,GRD2-Metropolitano Central ...,0.437000,4,30,52.440000
2,GRD3-Metropolitano Central ...,0.434667,3,25,32.600000
3,GRD4-Metropolitano Central ...,0.498000,6,29,86.652000
4,GRD5-Metropolitano Central ...,0.387000,4,20,30.960000
5,GRD6-Metropolitano Central ...,0.462333,5,25,57.791667
6,GRD7-Metropolitano Central ...,0.445000,4,32,56.960000
7,GRD8-Metropolitano Central ...,0.435667,4,28,48.794667
8,GRD9-Metropolitano Central ...,0.381333,5,25,47.666667
9,GRD10-Metropolitano Central ...,0.522333,10,28,146.253333
10,GRD1-Metropolitano Norte ...,0.593000,10,12,71.160000
11,GRD2-Metropolitano Norte ...,0.509000,4,10,20.360000
12,GRD3-Metropolitano Norte ...,0.367000,3,12,13.212000
13,GRD4-Metropolitano Norte ...,0.492000,6,8,23.616000
14,GRD5-Metropolitano Norte ...,0.524000,4,8,16.768000
15,GRD6-Metropolitano Norte ...,0.405000,5,12,24.300000
16,GRD7-Metropolitano Norte ...,0.571000,4,13,29.692000
17,GRD8-Metropolitano Norte ...,0.474000,4,8,15.168000
18,GRD9-Metropolitano Norte ...,0.498000,5,7,17.430000
19,GRD10-Metropolitano Norte ...,0.305000,10,16,48.800000
20,GRD1-Metropolitano Occidente ...,0.490500,10,32,156.960000
21,GRD2-Metropolitano Occidente ...,0.421250,4,26,43.810000
22,GRD3-Metropolitano Occidente ...,0.459000,3,33,45.441000
23,GRD4-Metropolitano Occidente ...,0.388750,6,20,46.650000
24,GRD5-Metropolitano Occidente ...,0.510250,4,28,57.148000
25,GRD6-Metropolitano Occidente ...,0.412250,5,25,51.531250
26,GRD7-Metropolitano Occidente ...,0.456000,4,34,62.016000
27,GRD8-Metropolitano Occidente ...,0.369250,4,22,32.494000
28,GRD9-Metropolitano Occidente ...,0.489750,5,17,41.628750
29,GRD10-Metropolitano Occidente ...,0.365500,10,20,73.100000
30,GRD1-Metropolitano Oriente ...,0.426000,10,32,136.320000
31,GRD2-Metropolitano Oriente ...,0.440500,4,39,68.718000
32,GRD3-Metropolitano Oriente ...,0.448500,3,36,48.438000
33,GRD4-Metropolitano Oriente ...,0.443750,6,31,82.537500
34,GRD5-Metropolitano Oriente ...,0.520000,4,35,72.800000
35,GRD6-Metropolitano Oriente ...,0.396250,5,42,83.212500
36,GRD7-Metropolitano Oriente ...,0.403000,4,44,70.928000
37,GRD8-Metropolitano Oriente ...,0.470500,4,39,73.398000
38,GRD9-Metropolitano Oriente ...,0.423500,5,37,78.347500
39,GRD10-Metropolitano Oriente ...,0.430750,10,41,176.607500
40,GRD1-Metropolitano Sur ...,0.515200,10,23,118.496000
41,GRD2-Metropolitano Sur ...,0.446800,4,35,62.552000
42,GRD3-Metropolitano Sur ...,0.542800,3,37,60.250800
43,GRD4-Metropolitano Sur ...,0.439000,6,31,81.654000
44,GRD5-Metropolitano Sur ...,0.519000,4,34,70.584000
45,GRD6-Metropolitano Sur ...,0.403800,5,33,66.627000
46,GRD7-Metropolitano Sur ...,0.389200,4,26,40.476800
47,GRD8-Metropolitano Sur ...,0.515200,4,31,63.884800
48,GRD9-Metropolitano Sur ...,0.489000,5,40,97.800000
49,GRD10-Metropolitano Sur ...,0.383600,10,33,126.588000
50,GRD1-Metropolitano Sur Oriente ...,0.528750,10,26,137.475000
51,GRD2-Metropolitano Sur Oriente ...,0.518000,4,15,31.080000
52,GRD3-Metropolitano Sur Oriente ...,0.468250,3,24,33.714000
53,GRD4-Metropolitano Sur Oriente ...,0.476750,6,19,54.349500
54,GRD5-Metropolitano Sur Oriente ...,0.483750,4,18,34.830000
55,GRD6-Metropolitano Sur Oriente ...,0.445750,5,24,53.490000
56,GRD7-Metropolitano Sur Oriente ...,0.489000,4,26,50.856000
57,GRD8-Metropolitano Sur Oriente ...,0.457250,4,21,38.409000
58,GRD9-Metropolitano Sur Oriente ...,0.470250,5,15,35.268750
59,GRD10-Metropolitano Sur Oriente ...,0.473750,10,27,127.912500

In [254]:

# Definir el tamaño del intervalo
intervalo = 10

# Calcular la suma en intervalos
suma_intervalos = []
for i in range(0, len(Reult7_F), intervalo):
    suma = Reult7_F.loc[i:i+intervalo-1, 'Costo'].sum()
    suma_intervalos.append(suma)

# Mostrar los resultados
suma_intervalos

[683.2716666666666,
 280.50600000000003,
 610.779,
 891.307,
 788.9133999999999,
 597.38475]

# Pregunta 8
#####

### 891.307 - 280.506 = 610,801

# Pregunta 9

### ¿Cuál servicio de salud tuvo el costo de instalación de las 8 camas más baratas, siendo el mínimo?

In [269]:
Hosp_sheet

,Nombre Servicio de Salud,Nombre Establecimiento,Área Cuidados Intensivos Adultos,Área Cuidados Intermedios Adulto,Total Camas Críticas,Máxima cantidad de camas a aumetar,Costo de instalar una cama [MM$],Costo de operación anual de una cama [MM$],Costo diario GRD1 [MM$],Costo diario GRD2 [MM$],Costo diario GRD3 [MM$],Costo diario GRD4 [MM$],Costo diario GRD5 [MM$],Costo diario GRD6 [MM$],Costo diario GRD7 [MM$],Costo diario GRD8 [MM$],Costo diario GRD9 [MM$],Costo diario GRD10 [MM$]
0,Metropolitano Norte ...,Complejo Hospitalario San José,11,33,44,10,1407,47.2,0.593,0.509,0.367,0.492,0.524,0.405,0.571,0.474,0.498,0.305
1,Metropolitano Occidente ...,Hospital Adalberto Steeger (Talagante),6,11,17,5,1263,62.1,0.493,0.357,0.429,0.382,0.469,0.386,0.543,0.362,0.564,0.333
2,Metropolitano Occidente ...,Hospital Dr. Félix Bulnes Cerda,3,6,9,5,1310,65.9,0.580,0.325,0.375,0.409,0.561,0.362,0.328,0.314,0.536,0.436
3,Metropolitano Occidente ...,Hospital San Juan de Dios,29,47,76,30,1066,39.2,0.482,0.554,0.564,0.331,0.438,0.509,0.544,0.410,0.441,0.359
4,Metropolitano Occidente ...,Instituto Traumatológico Dr. Teodoro Gebauer,12,6,18,5,1433,55.5,0.407,0.449,0.468,0.433,0.573,0.392,0.409,0.391,0.418,0.334
5,Metropolitano Central ...,Hospital Clínico San Borja-Arriarán,17,26,43,10,1347,63.1,0.509,0.363,0.575,0.534,0.367,0.567,0.576,0.482,0.320,0.574
6,Metropolitano Central ...,Hospital de Urgencia Asistencia Pública Dr. Al...,24,20,44,10,1256,44.5,0.468,0.509,0.343,0.391,0.390,0.404,0.457,0.411,0.330,0.568
7,Metropolitano Central ...,Hospital el Carmen,6,12,18,4,1368,49.7,0.444,0.439,0.386,0.569,0.404,0.416,0.302,0.414,0.494,0.425
8,Metropolitano Oriente ...,Hospital Del Salvador,22,24,46,12,1075,45.4,0.444,0.339,0.345,0.544,0.458,0.531,0.340,0.491,0.377,0.443
9,Metropolitano Oriente ...,Hospital Dr. Luis Tisné B.,8,16,24,8,1056,56.2,0.386,0.477,0.491,0.312,0.452,0.362,0.435,0.305,0.482,0.421
10,Metropolitano Oriente ...,Instituto de Neurocirugía Dr. Alfonso Asenjo,12,11,23,8,1256,36.6,0.376,0.481,0.476,0.407,0.573,0.302,0.535,0.520,0.407,0.420
11,Metropolitano Oriente ...,Instituto Nacional de Enfermedades Respiratori...,15,29,44,15,1422,63.0,0.498,0.465,0.482,0.512,0.597,0.390,0.302,0.566,0.428,0.439
12,Metropolitano Sur ...,Hospital Barros Luco Trudeau,31,43,74,25,1319,42.9,0.551,0.339,0.587,0.416,0.545,0.306,0.347,0.548,0.501,0.419
13,Metropolitano Sur ...,Hospital de Enfermedades Infecciosas Dr. Lucio...,11,9,20,5,1193,61.6,0.540,0.407,0.590,0.492,0.458,0.361,0.420,0.452,0.331,0.330
14,Metropolitano Sur ...,Hospital Dr. Exequiel González Cortés,23,8,31,5,1304,51.9,0.398,0.343,0.454,0.493,0.489,0.444,0.323,0.572,0.500,0.310
15,Metropolitano Sur ...,Hospital El Pino,12,20,32,9,1074,66.1,0.546,0.599,0.550,0.383,0.569,0.442,0.543,0.504,0.590,0.549
16,Metropolitano Sur ...,Hospital Parroquial de San Bernardo,6,10,16,4,1051,47.0,0.541,0.546,0.533,0.411,0.534,0.466,0.313,0.500,0.523,0.310
17,Metropolitano Sur Oriente ...,Complejo Hospitalario Dr. Sótero del Río,20,35,55,12,1203,40.6,0.560,0.388,0.584,0.458,0.451,0.595,0.336,0.525,0.472,0.403
18,Metropolitano Sur Oriente ...,Hospital Clínico de la Florida,9,15,24,5,1028,60.0,0.527,0.552,0.431,0.594,0.331,0.341,0.580,0.528,0.537,0.505
19,Metropolitano Sur Oriente ...,Hospital Metropolitano ( ex Militar ),12,20,32,5,1093,46.3,0.549,0.553,0.471,0.346,0.582,0.331,0.456,0.394,0.410,0.563
20,Metropolitano Sur Oriente ...,Hospital Padre Alberto Hurtado (San Ramón),6,10,16,5,1166,43.2,0.479,0.579,0.387,0.509,0.571,0.516,0.584,0.382,0.462,0.424

In [277]:
result9 = Hosp_sheet.groupby(['Nombre Servicio de Salud','Costo de instalar una cama [MM$]'])['Máxima cantidad de camas a aumetar'].sum().reset_index(name='Máxima cantidad de camas a aumetar')

Hosp_sheet_filtrado = Hosp_sheet[Hosp_sheet['Máxima cantidad de camas a aumetar'] > 8]
Hosp_sheet_filtrado


result9.sort_values(by=['Costo de instalar una cama [MM$]'],ascending = False)

,Nombre Servicio de Salud,Costo de instalar una cama [MM$],Máxima cantidad de camas a aumetar
7,Metropolitano Occidente ...,1433,5
11,Metropolitano Oriente ...,1422,15
3,Metropolitano Norte ...,1407,10
2,Metropolitano Central ...,1368,4
1,Metropolitano Central ...,1347,10
16,Metropolitano Sur ...,1319,25
6,Metropolitano Occidente ...,1310,5
15,Metropolitano Sur ...,1304,5
5,Metropolitano Occidente ...,1263,5
0,Metropolitano Central ...,1256,10
10,Metropolitano Oriente ...,1256,8
20,Metropolitano Sur Oriente ...,1203,12
14,Metropolitano Sur ...,1193,5
19,Metropolitano Sur Oriente ...,1166,5
18,Metropolitano Sur Oriente ...,1093,5
9,Metropolitano Oriente ...,1075,12
13,Metropolitano Sur ...,1074,9
4,Metropolitano Occidente ...,1066,30
8,Metropolitano Oriente ...,1056,8
12,Metropolitano Sur ...,1051,4
17,Metropolitano Sur Oriente ...,1028,5

In [260]:
Hosp_sheet_filtrado

,Nombre Servicio de Salud,Nombre Establecimiento,Área Cuidados Intensivos Adultos,Área Cuidados Intermedios Adulto,Total Camas Críticas,Máxima cantidad de camas a aumetar,Costo de instalar una cama [MM$],Costo de operación anual de una cama [MM$],Costo diario GRD1 [MM$],Costo diario GRD2 [MM$],Costo diario GRD3 [MM$],Costo diario GRD4 [MM$],Costo diario GRD5 [MM$],Costo diario GRD6 [MM$],Costo diario GRD7 [MM$],Costo diario GRD8 [MM$],Costo diario GRD9 [MM$],Costo diario GRD10 [MM$]
0,Metropolitano Norte ...,Complejo Hospitalario San José,11,33,44,10,1407,47.2,0.593,0.509,0.367,0.492,0.524,0.405,0.571,0.474,0.498,0.305
3,Metropolitano Occidente ...,Hospital San Juan de Dios,29,47,76,30,1066,39.2,0.482,0.554,0.564,0.331,0.438,0.509,0.544,0.410,0.441,0.359
5,Metropolitano Central ...,Hospital Clínico San Borja-Arriarán,17,26,43,10,1347,63.1,0.509,0.363,0.575,0.534,0.367,0.567,0.576,0.482,0.320,0.574
6,Metropolitano Central ...,Hospital de Urgencia Asistencia Pública Dr. Al...,24,20,44,10,1256,44.5,0.468,0.509,0.343,0.391,0.390,0.404,0.457,0.411,0.330,0.568
8,Metropolitano Oriente ...,Hospital Del Salvador,22,24,46,12,1075,45.4,0.444,0.339,0.345,0.544,0.458,0.531,0.340,0.491,0.377,0.443
11,Metropolitano Oriente ...,Instituto Nacional de Enfermedades Respiratori...,15,29,44,15,1422,63.0,0.498,0.465,0.482,0.512,0.597,0.390,0.302,0.566,0.428,0.439
12,Metropolitano Sur ...,Hospital Barros Luco Trudeau,31,43,74,25,1319,42.9,0.551,0.339,0.587,0.416,0.545,0.306,0.347,0.548,0.501,0.419
15,Metropolitano Sur ...,Hospital El Pino,12,20,32,9,1074,66.1,0.546,0.599,0.550,0.383,0.569,0.442,0.543,0.504,0.590,0.549
17,Metropolitano Sur Oriente ...,Complejo Hospitalario Dr. Sótero del Río,20,35,55,12,1203,40.6,0.560,0.388,0.584,0.458,0.451,0.595,0.336,0.525,0.472,0.403

# Pregunta 10

### ¿Cuál código permite determinar qué servicios de salud tienen más camas intermedias, que camas críticas?

In [281]:
hospitales = Hosp_sheet.loc[Hosp_sheet["Área Cuidados Intensivos Adultos"] < Hosp_sheet["Área Cuidados Intermedios Adulto"]]

hospitales[["Nombre Establecimiento","Área Cuidados Intensivos Adultos","Área Cuidados Intermedios Adulto"]]

,Nombre Establecimiento,Área Cuidados Intensivos Adultos,Área Cuidados Intermedios Adulto
0,Complejo Hospitalario San José,11,33
1,Hospital Adalberto Steeger (Talagante),6,11
2,Hospital Dr. Félix Bulnes Cerda,3,6
3,Hospital San Juan de Dios,29,47
5,Hospital Clínico San Borja-Arriarán,17,26
7,Hospital el Carmen,6,12
8,Hospital Del Salvador,22,24
9,Hospital Dr. Luis Tisné B.,8,16
11,Instituto Nacional de Enfermedades Respiratori...,15,29
12,Hospital Barros Luco Trudeau,31,43
15,Hospital El Pino,12,20
16,Hospital Parroquial de San Bernardo,6,10
17,Complejo Hospitalario Dr. Sótero del Río,20,35
18,Hospital Clínico de la Florida,9,15
19,Hospital Metropolitano ( ex Militar ),12,20
20,Hospital Padre Alberto Hurtado (San Ramón),6,10